### ISSUE TITLE
Support more editors with ace

### ISSUE THREAD

**Issue by pickfire** [ekzhang/rustpad#19]
https://github.com/ajaxorg/ace

Which is what rust-playground uses, using that can probably allow more keybindings like vim or emacs keys.

**Comment by ekzhang** [comment]
This is quite a bit of work, since it would require writing an extra operational transformation interface and handling Ace's event listeners + turning them into text operations. It would also increase the size of the JavaScript bundle we need to load significantly, and not all of the same languages would still be supported.

You're welcome to make a fork though, or use something like [Firepad](https://firepad.io/examples/#code-S4SUyVTyue). :)
