### ISSUE TITLE
Docker container SSL certificates

### ISSUE THREAD

**Issue by orhun** [ekzhang/rustpad#2]
Hey!

I'm using the given example command from README.md to run a `rustpad` instance on my server:

```sh
docker run --rm -dp 3030:3030 ekzhang/rustpad
```

But unfortunately I couldn't figure out how to enable SSL for the running instance. I have certificates on my server and I tried to give `net` access to the container but no luck. What am I supposed to do here?

I think It'd be nice to mention such case in the documentation.

**Comment by ekzhang** [comment]
Hi @orhun, thanks for looking into this. TLS configuration isn't in the documentation because the server doesn't have TLS support. You can configure a reverse proxy like Nginx for HTTPS and WebSocket. The public deployment is on DigitalOcean App Platform, which handles this automatically.

I think it is possible to add TLS support, as both warp and tokio-tungstenite can do this via rustls, but I'm not certain of the advantages of this over just using a reverse proxy.

**Comment by orhun** [comment]
Ok I managed to get it done by using Nginx reverse proxy:

```nginx
server {
  listen 443 ssl;

  # setup SSL certificates
  # ssl_certificate ...
  # ...

  location / {
   proxy_http_version 1.1;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
   proxy_pass http://localhost:3030/;
  }
}

```

**Comment by ekzhang** [comment]
Great, thanks for sharing your configuration!
