### ISSUE TITLE
Is it possible to run the code in the browser?

### ISSUE THREAD

**Issue by jackson-sandland** [ekzhang/rustpad#20]
Love that this is written in Rust. I'm wondering if it's possible to run the code in the shared editor?. If so, how do you do that?

**Comment by ekzhang** [comment]
Thanks Jackson! I appreciate the feedback. :)

While it would be great to run code in the browser, I think this adds a lot more complexity, so I don't think it fits within the scope of the project. A similar suggestion was also made in issue #3, and you can see my thoughts there.

If you make a free website that lets you run sandboxed code + easily collaboratively edit in the browser, I'm curious to hear how it turns out! It sounds like it could be a really useful app.
