### ISSUE TITLE
Render markdown option

### ISSUE THREAD

**Issue by sigaloid** [ekzhang/rustpad#41]
Would it be possible to enable an option when editing with Markdown, to render the markdown on the side? There are javascript libraries to do this, like md-block. 

This would make this project a viable alternative to [Etherpad](https://etherpad.org/) which would be awesome because this uses orders of magnitude less RAM than Etherpad (being Javascript-based).

**Comment by ekzhang** [comment]
Hi, thanks for the suggestion, and sorry for not being able to respond more quickly. Glad to hear that you're enjoying Rustpad and that it's been more performant than Etherpad for you. Unfortunately I think language-specific features are not in scope for Rustpad since it's strictly a collaborative editor with syntax highlighting.

However, if you're looking for a Markdown-based collaborative editor to use with others, I recommend [HackMD](https://hackmd.io/). It's a commercial offering, but their free plan has worked pretty well for me in the past.

**Comment by nicbarker** [comment]
Just for posterity and other users finding this issue through google, there is an open source markdown editor available here: https://github.com/Cveinnt/LetsMarkdown.com
