### ISSUE TITLE
State Persistence for volatile deployments

### ISSUE THREAD

**Issue by PeterGrace** [ekzhang/rustpad#6]
It appears that the current implementation keeps the state table in volatile memory (RAM) rather than committing it to disk.  As such, deploying this in a scenario where the service's lifetime is not guaranteed (container orchestration, e.g. kubernetes) the state would be lost in an eviction scenario.

It would be nice if there was a way to offload the state table into a somewhat more persistent datastore or use something like sqlite with a pvc in kubernetes to help maintain state.

**Comment by ekzhang** [comment]
Good point. Persisting to a SQLite file in a PVC would be okay, though maybe a more general solution would be to connect it via a database URL passed in as an environment variable?

This can probably be done by inserting some [sqlx](https://github.com/launchbadge/sqlx) queries at the right places in the code. I don't want database operations to be a server latency bottleneck though. Maybe Redis would work better for this use case. I will read into some OT server persistence strategies.

**Comment by 9SMTM6** [comment]
2 Things I noticed on cursory reading of this, without trying it myself so far:

* From my understanding SQLITE_URI is simply a file. People without much SQLite experience might not be aware of this, and think that setting this up is more complicated than it is. And adjustment in the documentation that says "simply create an empty file, mount it in the docker container, and provide its URI in this env-variable" would solve that.

* is there a easy way to clean up stuff that we no longer require? Delete them? Otherwise it could get out of hand at some point.

**Comment by orhun** [comment]
After seeing @9SMTM6's comment, I tried to run `rustpad` with state persistence, just to try it out:

```sh
$ touch rustpad.db
$ docker run --rm -e "SQLITE_URI=sqlite:///rustpad.db" -v "$(pwd)/rustpad.db:/rustpad.db:rw" --name=rustpad --user 1000:1000 -p 3030:3030 ekzhang/rustpad:latest
```

And got this error:

```
thread 'main' panicked at 'Unable to connect to SQLITE_URI: error returned from database: attempt to write a readonly database

Caused by:
    attempt to write a readonly database', rustpad-server/src/main.rs:22:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea about what could have possibly gone wrong?

Also, I pretty much agree, this should be mentioned somewhere in the documentation. I'm happy to submit a PR if I can make the command above run 🙂

**Comment by 9SMTM6** [comment]
Huh. Not entirely sure whats going on there, I tried it, got the same issue.

I fixed it though. Docker is VERY picky when it comes to mounting files, so I tried switching to mounting a directory instead, and it worked. Didn't have to create the file actually.

```sh

mkdir rustpad-persist
sudo docker run --rm -e "SQLITE_URI=sqlite:///persist/rustpad.db" -v "$(pwd)/rustpad-persist/:/persist" -p 3030:3030 ekzhang/rustpad:latest
```

worked for me.

It also created 2 other files, maybe thats the issue, or we didn't mount the file the right way.

**Comment by 9SMTM6** [comment]
Also, most of what I wanted in there is already in the Documentation, I didnt read it properly. It could use a reordering, as many people will probably skip it once they read the first sentence. It actually also says that one should mount a directory, though I'm not sure if thats due to aforementioned issue, or just because @ekzhang also tends to mount directories by default.

**Comment by orhun** [comment]
Ah, this worked for me too:

```sh
$ mkdir rustpad_db/
$ docker run --rm -e "SQLITE_URI=sqlite:///persist/rustpad.db" -v "$(pwd)/rustpad_db:/persist" --name=rustpad --user 1000:1000 -p 3030:3030 ekzhang/rustpad:latest
```

Thanks @9SMTM6 

Also, it seems that database is automatically created if not exist so mounting a directory is enough:

https://github.com/ekzhang/rustpad/blob/c98a6d7c4e22340e8d3a559e822a8a41fbbdd93a/rustpad-server/src/database.rs#L27-L29

**Comment by ekzhang** [comment]
Yes, you need to mount a directory rather than a single file. This is a limitation of Docker, see an explanation [here](https://stackoverflow.com/a/44950494/2514396). The database is created automatically if it does not exist.

**Comment by realalexandergeorgiev** [comment]
I was unable to make it work. Would have been nice to add a sh/ash/dash/bash into the container for debugging :(

**Comment by ekzhang** [comment]
If you're using Orbstack https://docs.orbstack.dev/features/debug
