### ISSUE TITLE
What's the use of WASM (if a backend server is needed anyway)?

### ISSUE THREAD

**Issue by jymchng** [ekzhang/rustpad#81]
Hi @ekzhang 

Thank you for this excellent piece of work.

I am looking to hook this up with a frontend code editor using @codemirror/collab.

Can you help me to understand why is there a need to have a WASM binary even though the OT is resolved/computed at the server?

Thank you.

**Comment by ekzhang** [comment]
Rustpad applies transformations on both client and server.

**Comment by jymchng** [comment]
> Rustpad applies transformations on both client and server.

Are you saying that there are two 'binaries', one on the server and another (a wasm binary) in the client, both applying the transformations parallelly?

Thank you.

**Comment by ekzhang** [comment]
No, that's not right

**Comment by jymchng** [comment]
Hi @ekzhang 

Thank you for sharing. Anyway, I still don't get it but it is okay, I'll use Rushlight instead.

Thank you for writing both.

**Comment by ekzhang** [comment]
No worries, it is a bit complex, I needed to take a while to understand the client-server ot model too

**Comment by orhun** [comment]
As far as I understand, `rustpad` uses the WASM backend to do the operational transformation operations since it would require much more resources/time to send the data to the server and process the response. Instead, they are calculated on user's browser. I might be wrong though - but that's what I remember from the time that I looked into `rustpad`'s code back in the day.

Just my 2 🪙
