### ISSUE TITLE
"Read the code" button nukes document contents

### ISSUE THREAD

**Issue by Zannick** [ekzhang/rustpad#91]
Only the user who clicked it can undo it (until they leave the page), otherwise contents are irrecoverable.

Surely this should create a new document or just link to the github file? It does not sound like a modify button, so it is a negative surprise for a user who joins an in-progress pad.

**Comment by ekzhang** [comment]
I understand your inconvenience but I also don't want to redesign this 3 years later

**Comment by Zannick** [comment]
That's a disappointing response, tbh. I can offer some suggestions so the amount of redesign work on your end is low. It was easy enough to find where to change, I could maybe submit a simple PR:

https://github.com/ekzhang/rustpad/blob/cbc5df8b4b2914fa1f13e328b0acd7649985c723/src/App.tsx#L285-L288

So my potential ideas for this are:
1. Change the text to "Edit the code" or "Edit our code" or "Try our code sample" or something
2. Remove the button entirely.
3. Replace the button onclick with a link to a new pad with default contents (don't know if this is possible).

Are there any of these you would consider accepting?

**Comment by ekzhang** [comment]
If you had made this suggestion 3 years earlier I probably would've taken it, but honestly nothing has changed since then, and I don't really want to nitpick my past work.

**Comment by Zannick** [comment]
I don't understand what you mean by past work given that you are still hosting rustpad.io and accepting PRs and issues. But ok.

**Comment by lukaslangrock** [comment]
Hi, I saw that you added a [confirmation dialog](https://github.com/ekzhang/rustpad/commit/aa4ee8560a59178cd249c18bd6a21caa502ff73e), even though you said you didn't plan to. Thank you so much for this!

But, I was confused at first because it would sometimes delete my document without asking, so I looked around and found out the dialog only appears when your document is at least [10 lines long](https://github.com/ekzhang/rustpad/blob/aa4ee8560a59178cd249c18bd6a21caa502ff73e/src/App.tsx#L118). I feel like that could be reduced to one or two lines, as even data loss of just a few lines can be quite annoying.

I didn't want to make a PR as it was just a small change, but I'd be happy to do so if you are too busy.
